### ISSUE TITLE
Update package description for Visual Studio 2019

### ISSUE THREAD

**Issue by pascalberger** [MNie/chocolatey-typescript-vs2017#2]
Visual Studio 2019 uses the same installer as Visual Studio 2017. This package therefore can also be used for Visual Studio 2019. It would be nice to have this mentioned in the package title and description (ID will still show vs2017 though).

**Comment by MNie** [comment]
updated (id also)

**Comment by pascalberger** [comment]
@MNie Thanks for the quick fix 👍 

If you update the ID you'll need to deprecate the old package (see [docs](https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package)). I probably wouldn't do this in this case.
Also you have updated the software name in the `chocolateyInstall.ps1` and `chocolateyUninstall.ps1`. This should be the display name of the Software, which probably doesn't match now (see [here](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md#118-set-softwarename) for more information).
